"""initial migration

Revision ID: c6c05ad7be6b
Revises: 
Create Date: 2024-09-20 14:13:40.617931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6c05ad7be6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_results',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('entities', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('text_length', sa.Integer(), nullable=True),
    sa.Column('contains_product_mention', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_review_results_review_id'), 'review_results', ['review_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_results_review_id'), table_name='review_results')
    op.drop_table('review_results')
    # ### end Alembic commands ###
